#!/usr/bin/env bash
# Copies ABIs from contracts/out into packages/abi (I-0.5, I-1.7). Run from anywhere.
#   packages/abi/<Name>.json  plain ABI JSON (Envio's contract import reads these)
#   packages/abi/abis.ts      the same ABIs `as const`, so viem types every call
set -euo pipefail
here="$(cd "$(dirname "$0")/.." && pwd)"
dest="$here/../packages/abi"
cd "$here" && forge build --silent

ts="$dest/abis.ts"
echo "// Generated by contracts/scripts/export-abi.sh. Do not edit by hand." > "$ts"
for name in CampaignVault CreatorReputation MockUSDC; do
  jq '.abi' "out/$name.sol/$name.json" > "$dest/$name.json"
  var="$(tr '[:upper:]' '[:lower:]' <<< "${name:0:1}")${name:1}Abi"
  { echo; echo "export const $var = $(jq '.abi' "out/$name.sol/$name.json") as const;"; } >> "$ts"
  echo "wrote packages/abi/$name.json"
done
echo "wrote packages/abi/abis.ts"
